- name: Install and build Dockerfile
  hosts: localhost
  become: true
  tasks:
    - name: Copy Dockerfile to the project directory
      copy:
        src: Dockerfile
        dest: /home/davezapanta/CPE232_ZapantaHOA11
        owner: davezapanta
        group: davezapanta
        mode: '0755'

    - name: Build Docker image
      shell:
        cmd: "docker build -t davezapanta /home/davezapanta/CPE232_ZapantaHOA11"
